# Generated by Django 4.2.16 on 2024-11-21 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_rename_movie_id_movie_movie_pk_alter_comment_movie_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='movie_pk',
        ),
        migrations.AlterField(
            model_name='movie',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
